export default function TermsOfServiceBody() {
    return (
        <div className="legal-prose space-y-10 [&_h2]:mt-12 [&_h2]:scroll-mt-28 [&_h2]:border-b [&_h2]:border-orange-100 [&_h2]:pb-3 [&_h2]:font-playfair [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:text-text-dark [&_h2:first-child]:mt-0 [&_h3]:mt-6 [&_h3]:font-semibold [&_h3]:text-text-dark [&_ul]:my-4 [&_ul]:list-disc [&_ul]:space-y-2 [&_ul]:pl-6 [&_p]:mb-4 [&_p]:leading-relaxed [&_strong]:font-semibold [&_strong]:text-text-dark">
            <section>
                <p className="mb-4 text-sm text-text-light italic">
                    These Terms of Service replace and supersede all prior versions (archived at the
                    bottom of this page) as of the effective date stated in the heading above.
                </p>
                <p className="mb-4 leading-relaxed">
                    These Terms of Service, and incorporated terms and policies below (together the
                    &quot;Terms&quot;), are an agreement between MyMatch.lk, a company incorporated in Sri Lanka,
                    located at [Your Business Address, Colombo/Sri Lanka], on behalf of itself and its
                    Affiliates (&quot;MyMatch,&quot; &quot;we,&quot; or &quot;us&quot;) and you (&quot;Customer,&quot;
                    &quot;you,&quot; or &quot;your&quot;) for the use of the MyMatch.lk matchmaking web application and
                    related services (defined below). By accessing, registering on, or using the Services,
                    you acknowledge and agree to be bound by these Terms, which include the Privacy Policy
                    and any applicable Data Processing Addendum.
                </p>
            </section>

            <section id="applicability">
                <h2>1. Applicability</h2>
                <h3>1.1 Individual vs. Company Use</h3>
                <p>
                    If you are agreeing to these Terms not as an individual but on behalf of a company,
                    government, or other entity (e.g., a matrimonial agency), then &quot;you&quot; or
                    &quot;Customer&quot; means such entity, and you represent that you have authority to bind
                    that entity. If you do not have such authority, do not use the Services.
                </p>
                <p>
                    For personal matchmaking use, it is recommended you do not use an employer-issued email
                    address. You remain solely responsible for your profile and interactions.
                </p>
                <h3>1.2 Age Requirement</h3>
                <p>
                    The Services are not for anyone under 18 years of age. By using MyMatch.lk, you confirm
                    that you are at least 18 years old. We do not knowingly collect data from minors.
                </p>
                <h3>1.3 When These Terms Do Not Apply</h3>
                <ul>
                    <li>
                        <strong>Employer-issued accounts:</strong> If your employer or a matrimonial agency
                        has registered you, their separate agreement with MyMatch governs your use.
                    </li>
                    <li>
                        <strong>Public community areas:</strong> Use of forums or public blogs on MyMatch.lk
                        (if any) is subject to separate community guidelines.
                    </li>
                </ul>
            </section>

            <section id="definitions">
                <h2>2. Definitions</h2>
                <ul>
                    <li>
                        <strong>2.1 &quot;Account&quot;</strong> means your personal matchmaking profile registered
                        via email or phone number.
                    </li>
                    <li>
                        <strong>2.2 &quot;Authorized User&quot;</strong> means any individual (match seeker) who
                        registers and maintains an active profile.
                    </li>
                    <li>
                        <strong>2.3 &quot;Customer Content&quot;</strong> means photos, biodata, preferences,
                        messages, and any other information you upload or generate via the Services.
                    </li>
                    <li>
                        <strong>2.4 &quot;Documentation&quot;</strong> refers to help guides, FAQs, and matchmaking
                        rules published on MyMatch.lk.
                    </li>
                    <li>
                        <strong>2.5 &quot;Match&quot;</strong> means a potential compatibility suggestion generated by
                        our algorithm based on your preferences and profile data.
                    </li>
                    <li>
                        <strong>2.6 &quot;Services&quot;</strong> means the MyMatch.lk web application, matching
                        engine, messaging system, profile hosting, and any related features.
                    </li>
                    <li>
                        <strong>2.7 &quot;Subscription Plan&quot;</strong> means paid tiers (e.g., Free, Premium)
                        that offer additional features such as unlimited messaging, verified badges, or priority
                        matching.
                    </li>
                    <li>
                        <strong>2.8 &quot;User&quot;</strong> means any registered member of MyMatch.lk.
                    </li>
                </ul>
            </section>

            <section id="account-registration">
                <h2>3. Account Registration & Security</h2>
                <p>
                    <strong>3.1</strong> You must provide accurate, truthful, and current information,
                    including your name, age, gender, location, and match preferences.
                </p>
                <p>
                    <strong>3.2</strong> You are responsible for safeguarding your login credentials. Do not
                    share your password with anyone.
                </p>
                <p>
                    <strong>3.3</strong> You agree to notify us immediately of any unauthorized use of your
                    Account at{' '}
                    <a
                        href="mailto:support@mymatch.lk"
                        className="font-semibold text-primary underline underline-offset-2 hover:text-primary-dark"
                    >
                        support@mymatch.lk
                    </a>
                    .
                </p>
                <p>
                    <strong>3.4</strong> One person may have only one active Account unless explicitly
                    permitted by MyMatch. Duplicate or fake accounts will be terminated.
                </p>
            </section>

            <section id="user-conduct">
                <h2>4. User Conduct & Prohibited Activities</h2>
                <p>You agree NOT to:</p>
                <ul>
                    <li>
                        Post false, misleading, or fraudulent biodata (e.g., wrong age, marital status, or
                        photos of another person).
                    </li>
                    <li>Harass, abuse, threaten, or stalk any other User.</li>
                    <li>
                        Share obscene, violent, illegal, or sexually explicit content (except as permitted
                        within private messaging, subject to reporting).
                    </li>
                    <li>
                        Use the Services for prostitution, human trafficking, financial scams, or any unlawful
                        purpose.
                    </li>
                    <li>Solicit money, investments, or donations from other Users.</li>
                    <li>Impersonate any person or entity.</li>
                    <li>Scrape, crawl, or copy any profile data without written permission.</li>
                    <li>Reverse engineer or attempt to extract our matching algorithm.</li>
                </ul>
                <p>
                    Violation may result in immediate account suspension or permanent ban, and referral to law
                    enforcement if illegal conduct is involved.
                </p>
            </section>

            <section id="matching-interactions">
                <h2>5. Matching & Interactions</h2>
                <p>
                    <strong>5.1</strong> Matches are generated by an automated algorithm based on the
                    preferences and profile information you provide. We do not guarantee:
                </p>
                <ul>
                    <li>Compatibility, success, or marriage.</li>
                    <li>The accuracy, safety, or honesty of any other User&apos;s profile.</li>
                    <li>That any match will respond or meet in person.</li>
                </ul>
                <p>
                    <strong>5.2</strong> You are solely responsible for your interactions with other Users. We
                    strongly recommend:
                </p>
                <ul>
                    <li>Verifying identities through video calls before meeting.</li>
                    <li>Meeting in public places for first dates.</li>
                    <li>Reporting suspicious behavior immediately.</li>
                </ul>
                <p>
                    <strong>5.3</strong> MyMatch.lk is not an introducer, marriage bureau, or agent. We do not
                    conduct background checks or verify the marital status, criminal history, or financial
                    standing of any User unless explicitly stated (e.g., a paid &quot;Verified&quot; badge with consent).
                </p>
            </section>

            <section id="subscriptions">
                <h2>6. Subscriptions, Payments & Refunds</h2>
                <p>
                    <strong>6.1</strong> Certain features (e.g., unlimited messaging, seeing who liked you,
                    verified badge) require a paid subscription.
                </p>
                <p>
                    <strong>6.2</strong> All fees are displayed in Sri Lankan Rupees (LKR) or as otherwise
                    indicated, inclusive of applicable taxes (e.g., VAT, SST depending on your location).
                </p>
                <p>
                    <strong>6.3</strong> Subscriptions automatically renew at the end of each billing cycle
                    (monthly/quarterly/yearly) unless you cancel at least 48 hours before renewal via your Account
                    settings.
                </p>
                <p>
                    <strong>6.4 Refund policy:</strong>
                </p>
                <ul>
                    <li>No refunds for partially used subscription periods.</li>
                    <li>
                        Refunds may be granted only if required by law (e.g., consumer protection in Sri Lanka)
                        or if a technical error on our side prevents service delivery.
                    </li>
                    <li>
                        Disputes should be sent to{' '}
                        <a
                            href="mailto:billing@mymatch.lk"
                            className="font-semibold text-primary underline underline-offset-2 hover:text-primary-dark"
                        >
                            billing@mymatch.lk
                        </a>{' '}
                        within 7 days of charge.
                    </li>
                </ul>
                <p>
                    <strong>6.5</strong> We reserve the right to change pricing with 30 days&apos; notice via email
                    or in-app notification.
                </p>
            </section>

            <section id="intellectual-property">
                <h2>7. Intellectual Property</h2>
                <p>
                    <strong>7.1 What we own:</strong> The MyMatch.lk software, matching algorithm, design,
                    logos, text, graphics, and underlying code are owned by MyMatch.lk (Pvt) Ltd or its
                    licensors.
                </p>
                <p>
                    <strong>7.2 What you own:</strong> You retain ownership of your photos, biodata, and
                    messages. However, by posting content, you grant MyMatch a non-exclusive, worldwide,
                    royalty-free license to host, store, display, and use that content solely to operate,
                    improve, and promote the Services (e.g., showing your profile to potential matches).
                </p>
                <p>
                    <strong>7.3</strong> You may not copy, modify, or redistribute any part of the Services
                    without written permission.
                </p>
            </section>

            <section id="termination">
                <h2>8. Termination & Account Deletion</h2>
                <p>
                    <strong>8.1 By you:</strong> You may delete your Account at any time via Settings → Delete
                    Account. This removes your profile, photos, and messages from active systems (backups may
                    persist for up to 30 days).
                </p>
                <p>
                    <strong>8.2 By us:</strong> We may suspend or terminate your Account immediately if you
                    violate these Terms, engage in fraudulent activity, or harm other Users.
                </p>
                <p>
                    <strong>8.3</strong> Upon termination, you lose access to paid subscription features without
                    refund for the unused period.
                </p>
            </section>

            <section id="disclaimers">
                <h2>9. Disclaimers & Limitation of Liability</h2>
                <h3>9.1 Disclaimer of warranties</h3>
                <p className="rounded-lg border border-slate-200 bg-slate-50 p-4 text-xs font-semibold uppercase leading-snug tracking-wide text-slate-800 md:text-sm">
                    THE SERVICES ARE PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE.&quot; TO THE MAXIMUM EXTENT PERMITTED BY LAW,
                    MYMATCH.LK DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR
                    A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE
                    UNINTERRUPTED, ERROR-FREE, OR SECURE, OR THAT ANY MATCH WILL LEAD TO A SUCCESSFUL RELATIONSHIP.
                </p>
                <h3>9.2 Limitation of liability</h3>
                <p className="rounded-lg border border-slate-200 bg-slate-50 p-4 text-xs font-semibold uppercase leading-snug tracking-wide text-slate-800 md:text-sm">
                    TO THE MAXIMUM EXTENT PERMITTED BY LAW, MYMATCH.LK AND ITS AFFILIATES SHALL NOT BE LIABLE FOR
                    ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF
                    PROFITS, DATA, OR OPPORTUNITIES, OR PHYSICAL OR EMOTIONAL HARM ARISING FROM IN-PERSON MEETINGS
                    WITH OTHER USERS, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL LIABILITY FOR
                    ANY CLAIM ARISING FROM THESE TERMS OR THE SERVICES SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN
                    THE 12 MONTHS PRECEDING THE CLAIM.
                </p>
            </section>

            <section id="governing-law">
                <h2>10. Governing Law & Dispute Resolution</h2>
                <p>
                    <strong>10.1</strong> These Terms shall be governed by the laws of Sri Lanka, without regard
                    to conflict of laws principles.
                </p>
                <p>
                    <strong>10.2</strong> Any dispute arising from or relating to these Terms or your use of the
                    Services shall first be attempted to be resolved through good faith negotiation within 30
                    days.
                </p>
                <p>
                    <strong>10.3</strong> If unresolved, the dispute shall be submitted to binding arbitration in
                    Colombo, Sri Lanka, in English, in accordance with the Arbitration Act No. 11 of 1995 of Sri
                    Lanka. Either party may also seek injunctive relief in courts of Colombo for IP or
                    confidentiality matters.
                </p>
                <p>
                    <strong>10.4</strong> For individual Users, you may also file a complaint with the Consumer
                    Affairs Authority of Sri Lanka if applicable.
                </p>
            </section>

            <section id="changes">
                <h2>11. Changes to These Terms</h2>
                <p>
                    We may update these Terms from time to time. Material changes (e.g., matching logic, refund
                    policy, data sharing) will be notified via email or prominent in-app notice at least 14 days in
                    advance. Continued use after the effective date constitutes acceptance.
                </p>
            </section>

            <section id="contact-archived">
                <h2>12. Contact Information</h2>
                <div className="rounded-xl border border-orange-100 bg-white p-6 shadow-[0_4px_24px_-8px_rgba(255,162,13,0.2)]">
                    <p className="mb-2 font-semibold text-text-dark">MyMatch.lk</p>
                    <p className="mb-4 text-sm">
                        [Your Registered Address, e.g., No. 123, Galle Road, Colombo 03, Sri Lanka]
                    </p>
                    <ul className="list-none space-y-2 !pl-0 text-sm">
                        <li>
                            <span className="font-semibold text-text-dark">Email:</span>{' '}
                            <a
                                href="mailto:support@mymatch.lk"
                                className="text-primary underline underline-offset-2 hover:text-primary-dark"
                            >
                                support@mymatch.lk
                            </a>
                        </li>
                        <li>
                            <span className="font-semibold text-text-dark">Billing disputes:</span>{' '}
                            <a
                                href="mailto:billing@mymatch.lk"
                                className="text-primary underline underline-offset-2 hover:text-primary-dark"
                            >
                                billing@mymatch.lk
                            </a>
                        </li>
                        <li>
                            <span className="font-semibold text-text-dark">For privacy matters:</span>{' '}
                            <a
                                href="mailto:privacy@mymatch.lk"
                                className="text-primary underline underline-offset-2 hover:text-primary-dark"
                            >
                                privacy@mymatch.lk
                            </a>
                        </li>
                        <li>
                            <span className="font-semibold text-text-dark">Archived versions:</span> Prior versions
                            of these Terms are available upon request to{' '}
                            <a
                                href="mailto:legal@mymatch.lk"
                                className="text-primary underline underline-offset-2 hover:text-primary-dark"
                            >
                                legal@mymatch.lk
                            </a>
                            .
                        </li>
                    </ul>
                </div>
                <p className="mt-6 text-sm text-text-light italic">
                    Please replace bracketed placeholders with your official registered address and primary contact
                    details when publishing.
                </p>
            </section>
        </div>
    );
}
