'use client';

import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'si';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    'browseProfiles': 'Browse Profiles',
    'aboutUs': 'About Us',
    'successStories': 'Success Stories',
    'contactUs': 'Contact Us',
    'login': 'Login',
    'registerFree': 'Register Free',
    'myProfile': 'My Profile',
    'settings': 'Settings',
    'logout': 'Logout',
    'heroTitle': 'Find Your Perfect Life Partner with Confidence',
    'heroTitlePerfect': 'Perfect Life',
    'heroTitlePartner': 'Partner',
    'heroDescription': 'Join thousands of families who found meaningful connections through our trusted matrimonial platform. Verified profiles, secure communication, and dedicated matchmaking support.',
    'createFreeProfile': 'Create Free Profile',
    'searchProfiles': 'Search Profiles',
    'verifiedProfiles': 'Verified Profiles',
    'successStoriesCount': 'Success Stories',
    'trustedMatchmakers': 'Trusted Matchmakers',
    'quickSearch': 'Quick Search',
    'imLookingFor': "I'm looking for",
    'ageFrom': 'Age From',
    'ageTo': 'Age To',
    'religion': 'Religion',
    'district': 'District',
    'searchNow': 'Search Now',
    // Features Section
    'findTheOne': 'Find the One',
    'findRealConnection': 'Find real connection',
    'featuresDescription': "If you're serious about finding your life partner, VivahaBandhu is for you. With one of the largest networks of verified profiles in Sri Lanka, connecting families and finding your perfect match has never been more trusted and secure.",
    'familyValues': 'Family Values & Cultural Understanding',
    'familyValuesDesc': 'We respect and understand your family traditions, cultural background, and values to find matches that align with your expectations and beliefs.',
    'verifiedTrusted': 'Verified & Trusted Profiles',
    'verifiedTrustedDesc': 'Every profile is thoroughly verified for authenticity. We ensure background checks, family verification, and genuine information for your peace of mind.',
    'personalMatchmaking': 'Personal Matchmaking Consultation',
    'personalMatchmakingDesc': 'Our experienced matchmakers conduct detailed consultations to understand your preferences, family expectations, and create a personalized matching strategy.',
    // How It Works
    'howItWorks': 'How It Works',
    'howItWorksDesc': 'Finding your life partner is easy with our simple 4-step process.',
    'createAccount': 'Create Account',
    'createAccountDesc': 'Register free and set up your account with basic details',
    'createProfile': 'Create Profile',
    'createProfileDesc': 'Add detailed profile information for yourself or family member',
    'browseMatch': 'Browse & Match',
    'browseMatchDesc': 'Search profiles and get smart suggestions based on preferences',
    'connect': 'Connect',
    'connectDesc': 'Express interest and connect when both parties accept',
    // Profiles Section
    'featuredProfiles': 'Featured Profiles',
    'featuredProfilesDesc': 'Browse through our verified profiles and find your perfect match today.',
    'verified': '✓ Verified',
    'match': 'Match',
    'viewAllProfiles': 'View All Profiles →',
    'subscribeToView': 'Subscribe to view full profile details',
    'upgradeNow': 'Upgrade Now',
    // Top Profiles
    'topLiveProfiles': 'Top Live Profiles',
    'topLiveProfilesDesc': 'Profiles that are currently active and looking for matches now.',
    'viewProfile': 'View Profile',
    'onlineNow': 'Online now',
    // Matchmaker Section
    'forProfessionals': 'For Professionals',
    'areYouMatchmaker': 'Are You a Matchmaker?',
    'matchmakerDesc': 'Join our platform as a professional matchmaker and help families find perfect matches. Create and manage multiple profiles under your account.',
    'unlimitedProfiles': 'Unlimited Profiles',
    'unlimitedProfilesDesc': 'Create unlimited profiles under your account',
    'clientDashboard': 'Client Dashboard',
    'clientDashboardDesc': 'Dashboard to manage all your clients',
    'verifiedBadge': 'Verified Badge',
    'verifiedBadgeDesc': 'Special matchmaker badge for credibility',
    'prioritySupport': 'Priority Support',
    'prioritySupportDesc': 'Priority support and featured listings',
    'bulkCommunication': 'Bulk Communication',
    'bulkCommunicationDesc': 'Bulk communication tools',
    'registerAsMatchmaker': 'Register as Matchmaker',
    'yourClientProfiles': 'Your Client Profiles',
    'addNewProfile': 'Add New Profile',
    // Blog Section
    'blogAdvice': 'Blog & Advice',
    'blogAdviceDesc': 'Expert tips for a successful marriage and wedding planning.',
    'readMore': 'Read More →',
    // FAQ Section
    'faq': 'Frequently Asked Questions',
    'faqDesc': "Have questions? We're here to help.",
    'account': 'Account',
    'subscription': 'Subscription',
    'privacy': 'Privacy',
    'accountProfile': 'Account & Profile',
    'howDoIRegister': 'How do I register?',
    'howDoIRegisterDesc': 'Simply click on the Register button, provide your basic details, and verify your email. It takes less than 2 minutes!',
    'isItFree': 'Is it free to create a profile?',
    'isItFreeDesc': 'Yes, registration and profile creation are completely free. You can also express interest in other members for free.',
    'premiumBenefits': 'What are the premium benefits?',
    'premiumBenefitsDesc': 'Premium members can view contact numbers, send unlimited messages, see who viewed their profile, and get priority support.',
    'canICancel': 'Can I cancel my subscription?',
    'canICancelDesc': 'Yes, you can cancel your subscription at any time. Your benefits will continue until the end of the billing period.',
    'whoCanSeeContact': 'Who can see my contact details?',
    'whoCanSeeContactDesc': 'Only Premium members can view your contact details, and only if you have chosen to make them visible to Premium members.',
    // Pricing Section
    'pricingPlans': 'Pricing Plans',
    'pricingPlansDesc': 'Choose the plan that fits your needs. No hidden fees.',
    'free': 'Free',
    'gold': 'Gold',
    'diamond': 'Diamond',
    'mostPopular': 'Most Popular',
    'addPhotos': 'Add Photos',
    'sendInterest': 'Send Interest',
    'viewContactInfo': 'View Contact Info',
    'directChat': 'Direct Chat',
    'allGoldFeatures': 'All Gold Features',
    'viewContactUnlimited': 'View Contact Info (Unlimited)',
    'profileBoost': 'Profile Boost',
    'featuredListing': 'Featured Listing',
    'personalAssistant': 'Personal Assistant',
    'getStarted': 'Get Started',
    'goPremium': 'Go Premium',
    // Footer
    'footerTagline': 'The most trusted matrimonial service for Sri Lankans worldwide.',
    'quickLinks': 'Quick Links',
    'forMatchmakers': 'For Matchmakers',
    'support': 'Support',
    'helpCenter': 'Help Center',
    'safetyTips': 'Safety Tips',
    'reportMisuse': 'Report Misuse',
    'legal': 'Legal',
    'privacyPolicy': 'Privacy Policy',
    'termsOfService': 'Terms of Service',
    'cookiePolicy': 'Cookie Policy',
    'refundPolicy': 'Refund Policy',
    'allRightsReserved': '© 2026 VivahaBandhu. All rights reserved.',
    'madeWithLove': 'Made with ❤️ in Sri Lanka',
    // About page
    'aboutHeroDesc': 'We are committed to helping you find meaningful connections with trust and care at the heart of everything we do.',
    'backToHome': 'Back to Home',
    'whoAreWe': 'Who are we',
    'whoAreWePara1': 'We are a team of passionate individuals who believe that everyone deserves to find a meaningful connection. Our platform is built on values of trust, authenticity, and care—helping people meet like-minded partners in a safe and welcoming space.',
    'whoAreWePara2': 'From our founders to our support team, we are committed to creating an experience that puts your happiness and safety first. We continuously improve our matching technology and community guidelines so you can focus on what matters: building real relationships.',
    'whoAreWeBullet1': 'Trust and safety at the core of everything we do',
    'whoAreWeBullet2': 'A diverse team that understands your journey',
    'whoAreWeBullet3': 'Dedicated to helping you find your perfect match',
    'pureLoveQuote': '"Pure love is not about grand promises or perfect moments. It is about two hearts choosing each other every day, even when life is imperfect. It is the quiet understanding in silence, the gentle patience during storms, and the unshakable trust that stays when everything else fades. True love remains pure because it asks for nothing, yet gives everything."',
    'ourSpecialtySubtitle': 'Premium Matrimonial Services for Sri Lankan Youth',
    'ourSpecialty': 'Our Specialty',
    'ourSpecialtyIntro': 'At MyMatch.lk, we specialize in providing top-quality matrimonial services for the Sri Lankan youth community. By combining trusted traditions with the latest technological innovations, we make finding your life partner a smarter, smoother, and more meaningful experience.',
    'specialtyAdvancedTech': 'Advanced Technology',
    'specialtyAdvancedTechText': 'MyMatch.lk leverages the power of AI to revolutionize matchmaking. Our intelligent system improves compatibility matching and introduces a modern approach to the traditional proposal-search process, making your journey faster, personalized, and more effective.',
    'specialtyHoroscope': 'Free Horoscope Matching',
    'specialtyHoroscopeText': 'We respect cultural traditions while embracing technology. MyMatch.lk offers free horoscope matching so you can easily check compatibility while keeping traditional values intact.',
    'specialtySecure': 'Secure & Private Profiles',
    'specialtySecureText': 'Your privacy is our top priority. MyMatch.lk allows you to browse proposals anonymously. Personal details such as phone numbers and photos are shared only with your consent, keeping you fully in control of your information.',
    'specialtyTrusted': 'Trusted & Reliable',
    'specialtyTrustedText': 'As a leading matrimonial service in Sri Lanka, MyMatch.lk has earned the trust of thousands. With over 15,000 five-star reviews on our Google profile, we have a proven track record of helping brides and grooms find their soulmates safely and successfully.',
    'startYourJourney': 'Start your journey',
    'findYourSoulmateNow': 'Find Your Soulmate Now',
    'findYourSoulmateDesc': 'Join thousands who found their perfect match. Create your free profile and let destiny begin.',
    'successStoriesDetail': 'Real couples who found love through MyMatch.lk. Read how we help bring families together and create lasting partnerships.',
    'story1Couple': 'Nadeesha & Rajitha',
    'story1Quote': 'We connected through MyMatch.lk and our families clicked from the first meeting. The horoscope matching gave us confidence, and six months later we got engaged. Thank you for making it so easy and trustworthy.',
    'story2Couple': 'Dilshan & Anjali',
    'story2Quote': 'I was skeptical about online matrimonial sites until my sister found her partner here. I created my profile, got genuine proposals, and found Anjali within a year. We married in 2024 and could not be happier.',
    'story3Couple': 'Chaminda & Sandya',
    'story3Quote': 'Both of us wanted a platform that respected our culture and privacy. MyMatch.lk felt safe—we could browse at our pace and share details only when ready. Our wedding was in Colombo and our families are still grateful.',
    'getInTouch': 'Get in Touch',
    'getInTouchSub': "I'd like to hear from you!",
    'contactIntro': 'If you have any inquiries or just want to say hi, please use the contact form!',
    'contactCareDetail': 'Experiencing issues with registration or login on MyMatch.lk? Reach out to our customer care at 0759876543. You can also message us via WhatsApp or Viber anytime.',
    'contactEmail': 'support@mymatch.lk',
    'firstName': 'First Name',
    'lastName': 'Last Name',
    'emailRequired': 'Email *',
    'messageLabel': 'Message',
    'sendButton': 'Send',
  },
  si: {
    'browseProfiles': 'පැතිකඩ පිරික්සන්න',
    'aboutUs': 'අප ගැන',
    'successStories': 'සාර්ථක කතා',
    'contactUs': 'අප හා සම්බන්ධ වන්න',
    'login': 'ඇතුළු වන්න',
    'registerFree': 'නොමිලේ ලියාපදිංචි වන්න',
    'myProfile': 'මගේ පැතිකඩ',
    'settings': 'සැකසීම්',
    'logout': 'ඉවත් වන්න',
    'heroTitle': 'විශ්වාසයෙන් ඔබේ පරිපූර්ණ ජීවිත හවුල්කරු සොයන්න',
    'heroTitlePerfect': 'පරිපූර්ණ ජීවිත',
    'heroTitlePartner': 'හවුල්කරු',
    'heroDescription': 'අපගේ විශ්වාසදායක විවාහ මාර්ගගත වේදිකාව හරහා අර්ථවත් සම්බන්ධතා සොයාගත් දහස් ගණනක පවුල්වලට සම්බන්ධ වන්න. සත්‍යාපනය කළ පැතිකඩ, ආරක්ෂිත සන්නිවේදනය සහ කැපවූ ගැලපීමේ සහාය.',
    'createFreeProfile': 'නොමිලේ පැතිකඩක් සාදන්න',
    'searchProfiles': 'පැතිකඩ සොයන්න',
    'verifiedProfiles': 'සත්‍යාපනය කළ පැතිකඩ',
    'successStoriesCount': 'සාර්ථක කතා',
    'trustedMatchmakers': 'විශ්වාසදායක ගැලපීම් කරන්නන්',
    'quickSearch': 'ක්ෂණික සෙවීම',
    'imLookingFor': 'මම සොයන්නේ',
    'ageFrom': 'වයස සිට',
    'ageTo': 'වයස දක්වා',
    'religion': 'ආගම',
    'district': 'දිස්ත්‍රික්කය',
    'searchNow': 'දැන් සොයන්න',
    // Features Section
    'findTheOne': 'එක සොයන්න',
    'findRealConnection': 'සැබෑ සම්බන්ධතාවයක් සොයන්න',
    'featuresDescription': 'ඔබ ඔබේ ජීවිත හවුල්කරු සොයා ගැනීමට බැඳී සිටින්නේ නම්, VivahaBandhu ඔබටමයි. ශ්‍රී ලංකාවේ සත්‍යාපනය කළ පැතිකඩවල විශාලතම ජාලයක් සමඟ, පවුල් සම්බන්ධ කර ඔබේ පරිපූර්ණ ගැලපීම සොයා ගැනීම කිසිදා වඩා විශ්වාසදායක සහ ආරක්ෂිත නොවීය.',
    'familyValues': 'පවුල් අගයන් සහ සංස්කෘතික අවබෝධය',
    'familyValuesDesc': 'ඔබේ පවුල් සම්ප්‍රදායන්, සංස්කෘතික පසුබිම සහ අගයන් අපි ගරු කරන අතර අවබෝධ කරන අතර, ඔබේ අපේක්ෂාවන් සහ විශ්වාසයන් සමඟ ගැලපෙන ගැලපීම් සොයා ගනිමු.',
    'verifiedTrusted': 'සත්‍යාපනය කළ සහ විශ්වාසදායක පැතිකඩ',
    'verifiedTrustedDesc': 'සෑම පැතිකඩක්ම සත්‍යාපනය සඳහා සම්පූර්ණයෙන් සත්‍යාපනය කරනු ලැබේ. ඔබේ සිතේ සාමය සඳහා පසුබිම් පරීක්ෂා, පවුල් සත්‍යාපනය සහ සැබෑ තොරතුරු සහතික කරන්නෙමු.',
    'personalMatchmaking': 'පුද්ගලික ගැලපීමේ උපදේශනය',
    'personalMatchmakingDesc': 'අපගේ අත්දැකීම් සහිත ගැලපීම් කරන්නන් ඔබේ මනාප, පවුල් අපේක්ෂාවන් අවබෝධ කර ගැනීමට සහ පුද්ගලීකරණය කළ ගැලපීමේ උපායමාර්ගයක් නිර්මාණය කිරීමට සවිස්තරාත්මක උපදේශන පවත්වයි.',
    // How It Works
    'howItWorks': 'එය ක්‍රියා කරන ආකාරය',
    'howItWorksDesc': 'අපගේ සරල පියවර 4 ක් සහිත ක්‍රියාවලිය සමඟ ඔබේ ජීවිත හවුල්කරු සොයා ගැනීම පහසුය.',
    'createAccount': 'ගිණුමක් සාදන්න',
    'createAccountDesc': 'නොමිලේ ලියාපදිංචි වී මූලික තොරතුරු සමඟ ඔබේ ගිණුම සැකසීම',
    'createProfile': 'පැතිකඩක් සාදන්න',
    'createProfileDesc': 'ඔබට හෝ පවුල් සාමාජිකයෙකුට සවිස්තරාත්මක පැතිකඩ තොරතුරු එක් කරන්න',
    'browseMatch': 'පිරික්සන්න සහ ගැලපීම',
    'browseMatchDesc': 'පැතිකඩ සොයා ගැනීම සහ මනාප මත පදනම්ව බුද්ධිමත් යෝජනා ලබා ගැනීම',
    'connect': 'සම්බන්ධ වන්න',
    'connectDesc': 'උනන්දුව ප්‍රකාශ කරන්න සහ දෙපාර්ශ්වයම පිළිගත් විට සම්බන්ධ වන්න',
    // Profiles Section
    'featuredProfiles': 'විශේෂ පැතිකඩ',
    'featuredProfilesDesc': 'අපගේ සත්‍යාපනය කළ පැතිකඩ හරහා පිරික්සා අදම ඔබේ පරිපූර්ණ ගැලපීම සොයා ගන්න.',
    'verified': '✓ සත්‍යාපනය කළ',
    'match': 'ගැලපීම',
    'viewAllProfiles': 'සියලුම පැතිකඩ බලන්න →',
    'subscribeToView': 'සම්පූර්ණ පැතිකඩ තොරතුරු බැලීමට දායක වන්න',
    'upgradeNow': 'දැන් උත්ශ්‍රේණි කරන්න',
    // Top Profiles
    'topLiveProfiles': 'ඉහළම සජීවී පැතිකඩ',
    'topLiveProfilesDesc': 'දැනට ක්‍රියාකාරී වන සහ දැන් ගැලපීම් සොයන පැතිකඩ.',
    'viewProfile': 'පැතිකඩ බලන්න',
    'onlineNow': 'දැන් මාර්ගගත',
    // Matchmaker Section
    'forProfessionals': 'වෘත්තීයවේදීන් සඳහා',
    'areYouMatchmaker': 'ඔබ ගැලපීම් කරන්නෙක්ද?',
    'matchmakerDesc': 'වෘත්තීය ගැලපීම් කරන්නෙකු ලෙස අපගේ වේදිකාවට සම්බන්ධ වී පවුල්වලට පරිපූර්ණ ගැලපීම් සොයා ගැනීමට උදව් කරන්න. ඔබේ ගිණුම යටතේ බහු පැතිකඩ නිර්මාණය කර කළමනාකරණය කරන්න.',
    'unlimitedProfiles': 'අසීමිත පැතිකඩ',
    'unlimitedProfilesDesc': 'ඔබේ ගිණුම යටතේ අසීමිත පැතිකඩ නිර්මාණය කරන්න',
    'clientDashboard': 'සේවාදායක උපකරණ පුවරුව',
    'clientDashboardDesc': 'ඔබේ සියලුම සේවාදායකයන් කළමනාකරණය කිරීමට උපකරණ පුවරුව',
    'verifiedBadge': 'සත්‍යාපනය කළ ලාංඡනය',
    'verifiedBadgeDesc': 'විශ්වාසදායකත්වය සඳහා විශේෂ ගැලපීම් කරන්නාගේ ලාංඡනය',
    'prioritySupport': 'ප්‍රමුඛ සහාය',
    'prioritySupportDesc': 'ප්‍රමුඛ සහාය සහ විශේෂ ලැයිස්තු',
    'bulkCommunication': 'සමූහ සන්නිවේදනය',
    'bulkCommunicationDesc': 'සමූහ සන්නිවේදන මෙවලම්',
    'registerAsMatchmaker': 'ගැලපීම් කරන්නෙකු ලෙස ලියාපදිංචි වන්න',
    'yourClientProfiles': 'ඔබේ සේවාදායක පැතිකඩ',
    'addNewProfile': 'නව පැතිකඩක් එක් කරන්න',
    // Blog Section
    'blogAdvice': 'බ්ලොග් සහ උපදෙස්',
    'blogAdviceDesc': 'සාර්ථක විවාහයක් සහ විවාහ සැලසුම් සඳහා වෘත්තීය උපදෙස්.',
    'readMore': 'තවත් කියවන්න →',
    // FAQ Section
    'faq': 'නිතර අසන ප්‍රශ්න',
    'faqDesc': 'ප්‍රශ්න තිබේද? අපි උදව් කිරීමට සූදානම්.',
    'account': 'ගිණුම',
    'subscription': 'දායකත්වය',
    'privacy': 'රහස්‍යතාව',
    'accountProfile': 'ගිණුම සහ පැතිකඩ',
    'howDoIRegister': 'මම ලියාපදිංචි වන්නේ කෙසේද?',
    'howDoIRegisterDesc': 'ලියාපදිංචි වීමේ බොත්තම ක්ලික් කරන්න, ඔබේ මූලික තොරතුරු සපයන්න, සහ ඔබේ විද්‍යුත් තැපෑල සත්‍යාපනය කරන්න. මිනිත්තු 2 කට අඩු කාලයක් ගත වේ!',
    'isItFree': 'පැතිකඩක් නිර්මාණය කිරීම නොමිලේද?',
    'isItFreeDesc': 'ඔව්, ලියාපදිංචි වීම සහ පැතිකඩ නිර්මාණය කිරීම සම්පූර්ණයෙන්ම නොමිලේ. ඔබට වෙනත් සාමාජිකයින් කෙරෙහි උනන්දුව ප්‍රකාශ කිරීමටද නොමිලේ.',
    'premiumBenefits': 'වාරික වාසි මොනවාද?',
    'premiumBenefitsDesc': 'වාරික සාමාජිකයින්ට දුරකථන අංක බැලීමට, අසීමිත පණිවිඩ යැවීමට, ඔවුන්ගේ පැතිකඩ බැලූ අය දැකීමට සහ ප්‍රමුඛ සහාය ලබා ගැනීමට හැකිය.',
    'canICancel': 'මම මගේ දායකත්වය අවලංගු කළ හැකිද?',
    'canICancelDesc': 'ඔව්, ඔබට ඕනෑම වේලාවක ඔබේ දායකත්වය අවලංගු කළ හැකිය. ඔබේ වාසි බිල්පත් කාලය අවසන් වන තෙක් අඛණ්ඩව පවතී.',
    'whoCanSeeContact': 'මගේ සම්බන්ධතා තොරතුරු කවුරුන්ට දැකිය හැකිද?',
    'whoCanSeeContactDesc': 'වාරික සාමාජිකයින්ට පමණක් ඔබේ සම්බන්ධතා තොරතුරු බැලීමට හැකිය, සහ ඔබ වාරික සාමාජිකයින්ට දෘශ්‍යමාන කිරීමට තෝරා ගෙන තිබේ නම් පමණි.',
    // Pricing Section
    'pricingPlans': 'මිල නියමයන්',
    'pricingPlansDesc': 'ඔබේ අවශ්‍යතාවලට ගැලපෙන සැලැස්ම තෝරන්න. සැඟවුණු ගාස්තු නැත.',
    'free': 'නොමිලේ',
    'gold': 'රන්',
    'diamond': 'දියමන්ති',
    'mostPopular': 'වඩාත්ම ජනප්‍රිය',
    'addPhotos': 'ඡායාරූප එක් කරන්න',
    'sendInterest': 'උනන්දුව යවන්න',
    'viewContactInfo': 'සම්බන්ධතා තොරතුරු බලන්න',
    'directChat': 'සෘජු කතාබහ',
    'allGoldFeatures': 'සියලුම රන් විශේෂාංග',
    'viewContactUnlimited': 'සම්බන්ධතා තොරතුරු බලන්න (අසීමිත)',
    'profileBoost': 'පැතිකඩ උත්ශ්‍රේණිය',
    'featuredListing': 'විශේෂ ලැයිස්තුව',
    'personalAssistant': 'පුද්ගලික සහායක',
    'getStarted': 'ආරම්භ කරන්න',
    'goPremium': 'වාරික වෙත යන්න',
    // Footer
    'footerTagline': 'ලොව පුරා ශ්‍රී ලාංකිකයන් සඳහා වඩාත්ම විශ්වාසදායක විවාහ සේවාව.',
    'quickLinks': 'ක්ෂණික සබැඳි',
    'forMatchmakers': 'ගැලපීම් කරන්නන් සඳහා',
    'support': 'සහාය',
    'helpCenter': 'උදව් මධ්‍යස්ථානය',
    'safetyTips': 'ආරක්ෂිත උපදෙස්',
    'reportMisuse': 'අනිසි භාවිතය වාර්තා කරන්න',
    'legal': 'නීතිමය',
    'privacyPolicy': 'රහස්‍යතා ප්‍රතිපත්තිය',
    'termsOfService': 'සේවා කොන්දේසි',
    'cookiePolicy': 'කුකී ප්‍රතිපත්තිය',
    'refundPolicy': 'ආපසු ගෙවීමේ ප්‍රතිපත්තිය',
    'allRightsReserved': '© 2026 VivahaBandhu. සියලුම හිමිකම් ඇවිරිණි.',
    'madeWithLove': 'ශ්‍රී ලංකාවේ ❤️ සමඟ සාදන ලදී',
    // About page
    'aboutHeroDesc': 'අප කටයුතු සියල්ලේ හදවතේ විශ්වාසය සහ රැකවරණය තබාගෙන අර්ථවත් සම්බන්ධතා සොයා ගැනීමට ඔබට උදව් කිරීමට අපි කැපවී සිටිමු.',
    'backToHome': 'මුල් පිටුවට ආපසු',
    'whoAreWe': 'අපි කවුද',
    'whoAreWePara1': 'සැමටම අර්ථවත් සම්බන්ධතාවක් සොයා ගැනීමට අයිතිය ඇතැයි විශ්වාස කරන උද්යෝගී පුද්ගලයන්ගේ කණ්ඩායමක් අපි. විශ්වාසය, සැබෑබව සහ රැකවරණය යන අගයන් මත අපගේ වේදිකාව ගොඩනගා ඇති අතර, ආරක්ෂිත හා සාදරයෙන් පිළිගන්නා අවකාශයක එකම සිතැති හවුල්කරුවන් හමුවීමට අයට උදව් කරයි.',
    'whoAreWePara2': 'අපගේ සම්භාවකයන්ගේ සිට සහාය කණ්ඩායම දක්වා, ඔබේ සතුට සහ ආරක්ෂාව පළමු තැන තබා ගන්නා අත්දැකීමක් නිර්මාණය කිරීමට අපි කැපවී සිටිමු. ඔබ සැබෑ සම්බන්ධතා ගොඩනැගීම වැනි වැදගත් දේවල් වෙත අවධානය යොමු කළ හැකි පරිදි අපගේ ගැලපීම් තාක්ෂණය සහ සමාජ මාර්ගෝපදේශ අඛණ්ඩව වැඩිදියුණු කරන්නෙමු.',
    'whoAreWeBullet1': 'අප කරන සෑම දෙයකම හරය ලෙස විශ්වාසය සහ ආරක්ෂාව',
    'whoAreWeBullet2': 'ඔබේ ගමන අවබෝධ කර ගන්නා විවිධ කණ්ඩායමක්',
    'whoAreWeBullet3': 'ඔබේ පරිපූර්ණ ගැලපීම සොයා ගැනීමට උදව් කිරීමට කැපවී සිටී',
    'pureLoveQuote': '"පිරිසිදු ප්‍රේමය යනු මහා පොරොන්දු හෝ පරිපූර්ණ මොහොත් ගැන නොවේ. ජීවිතය අපූර්ණ වුවද සෑම දිනකම එකිනෙකා තෝරා ගන්නා හදවත් දෙක ගැනයි. නිශ්චලතාවයේ නිහඬ අවබෝධය, කුණාටු අතරතුර මෘදු ඉවසීම සහ අන් සියල්ල අඳුරු වූ විට පවතින නොසැලෙන විශ්වාසයයි. සැබෑ ප්‍රේමය කිසිදු දෙයක් ඉල්ලා නොසිට තවත් සියල්ල දෙන බැවින් පිරිසිදුව පවතී."',
    'ourSpecialtySubtitle': 'ශ්‍රී ලාංකික තරුණ ප්‍රජාව සඳහා වාරික විවාහ සේවා',
    'ourSpecialty': 'අපගේ විශේෂත්වය',
    'ourSpecialtyIntro': 'MyMatch.lk හි අපි ශ්‍රී ලාංකික තරුණ ප්‍රජාව සඳහා ඉහළ තත්ත්වයේ විවාහ සේවා සපයන අතර විශේෂිතයි. විශ්වාසනීය සම්ප්‍රදායන් නවතම තාක්ෂණික නව්‍යෝත්පාදන සමඟ ඒකාබද්ධ කිරීමෙන්, ඔබේ ජීවිත හවුල්කරු සොයා ගැනීම බුද්ධිමත්, සුමට සහ අර්ථවත් අත්දැකීමක් බවට පත් කරන්නෙමු.',
    'specialtyAdvancedTech': 'උසස් තාක්ෂණය',
    'specialtyAdvancedTechText': 'MyMatch.lk ගැලපීම් ක්‍රියාවලිය විප්ලවීය කිරීමට AI හි බලය භාවිතා කරයි. අපගේ බුද්ධිමත් පද්ධතිය ගැලපුම් ගැලපීම වැඩිදියුණු කරන අතර සම්ප්‍රදායික යෝජනා-සෙවීම් ක්‍රියාවලියට නවීන ප්‍රවේශයක් හඳුන්වා දෙයි, ඔබේ ගමන වේගවත්, පුද්ගලීකරණය කළ සහ වඩාත් ඵලදායී කරයි.',
    'specialtyHoroscope': 'නොමිලේ රාශි ගැලපීම',
    'specialtyHoroscopeText': 'අපි තාක්ෂණය පිළිගනිමින් සංස්කෘතික සම්ප්‍රදායන් ගරු කරමු. MyMatch.lk සම්ප්‍රදායික අගයන් අඛණ්ඩව තබා ගනිමින් ගැලපීම පහසුවෙන් පරීක්ෂා කළ හැකි නොමිලේ රාශි ගැලපීම් ලබා දෙයි.',
    'specialtySecure': 'ආරක්ෂිත හා පෞද්ගලික පැතිකඩ',
    'specialtySecureText': 'ඔබේ රහස්‍යතාව අපගේ පළමු ප්‍රමුඛතාවයයි. MyMatch.lk ඔබට නිර්නාමිකව යෝජනා පිරික්සීමට ඉඩ දෙයි. දුරකථන අංක සහ ඡායාරූප වැනි පෞද්ගලික තොරතුරු ඔබේ එකඟතාවයෙන් පමණක් බෙදා ගනු ලබන අතර ඔබේ තොරතුරු සම්පූර්ණයෙන් පාලනය කිරීමට ඔබට ඉඩ දෙයි.',
    'specialtyTrusted': 'විශ්වාසනීය හා විශ්වසනීය',
    'specialtyTrustedText': 'ශ්‍රී ලංකාවේ ප්‍රමුඛ විවාහ සේවාවක් ලෙස MyMatch.lk දහස් ගණනකගේ විශ්වාසය ලබා ඇත. අපගේ Google පැතිකඩෙහි 15,000 ට වැඩි පහක් තරු සමාලෝචන සමඟ, සිරිත් කාන්තාවන්ට සහ මනාපයන්ට ඔවුන්ගේ ආත්ම සහායිකාවන් ආරක්ෂිතව සහ සාර්ථකව සොයා ගැනීමට උදව් කිරීමේ ඔප්පු කළ වාර්තාව අපට ඇත.',
    'startYourJourney': 'ඔබේ ගමන ආරම්භ කරන්න',
    'findYourSoulmateNow': 'දැන් ඔබේ ආත්ම සහායිකාව සොයන්න',
    'findYourSoulmateDesc': 'පරිපූර්ණ ගැලපීම සොයා ගත් දහස් ගණනකට සම්බන්ධ වන්න. ඔබේ නොමිලේ පැතිකඩ සාදා අරම්භය ආරම්භ කරන්න.',
    'successStoriesDetail': 'MyMatch.lk හරහා ප්‍රේමය සොයා ගත් සැබෑ යුවළවරු. පවුල් එකට ගෙන ඒමට සහ තිරසාර හවුල්කාරිත්වයන් නිර්මාණය කිරීමට අප උදව් කරන ආකාරය කියවන්න.',
    'story1Couple': 'නදීෂා සහ රාජිතා',
    'story1Quote': 'අපි MyMatch.lk හරහා සම්බන්ධ වුණා, පළමු හමුවෙන්ම අපේ පවුල් එකට ගැලපුණා. රාශි ගැලපීම අපට විශ්වාසය ලබා දුන්නා, මාස හයකින් අපි විවාහයට එකඟ වුණා. එය එතරම් පහසු සහ විශ්වාසදායක කළ ඔබට ස්තූතියි.',
    'story2Couple': 'දිල්ෂාන් සහ අංජලී',
    'story2Quote': 'අන්තර්ජාල විවාහ අඩවි ගැන මට සැක තිබුණා, මගේ සහෝදරිය මෙහි ඇයගේ හවුල්කරු සොයා ගන්නා තෙක්. මම මගේ පැතිකඩ සාදා සැබෑ යෝජනා ලැබුණා, එක් වසරකින් අංජලී සොයා ගත්තා. අපි 2024 දී විවාහ වුණා සහ තවත් සතුටු නැහැ.',
    'story3Couple': 'චමින්ද සහ සන්ධ්‍යා',
    'story3Quote': 'අප දෙදෙනාටම අපේ සංස්කෘතිය සහ රහස්‍යතාව ගරු කරන වේදිකාවක් අවශ්‍ය වුණා. MyMatch.lk ආරක්ෂිත යැයි හැඟුණා—අපට අපේ වේගයෙන් පිරික්සිය හැකි වුණා, සූදානම් වුණාම තොරතුරු බෙදා ගත්තා. අපේ බංගලාව කොළඹ වුණා, අපේ පවුල් තවමත් කෘතඥයි.',
    'getInTouch': 'අප හා සම්බන්ධ වන්න',
    'getInTouchSub': 'ඔබෙන් අසන්න මට අවශ්‍යයි!',
    'contactIntro': 'ප්‍රශ්න තිබේ නම් හෝ යාච්ඤා කිරීමට අවශ්‍ය නම්, කරුණාකර ලියාපදිංචි පෝරමය භාවිතා කරන්න!',
    'contactCareDetail': 'MyMatch.lk හි ලියාපදිංචි වීම හෝ ඇතුළු වීමේ ගැටළු තිබේද? අපගේ රැකියා සේවාවට 0759876543 දක්වා අමතන්න. ඔබට WhatsApp හෝ Viber හරහා ඕනෑම වේලාවක අපට පණිවිඩ යැවිය හැකිය.',
    'contactEmail': 'support@mymatch.lk',
    'firstName': 'මුල් නම',
    'lastName': 'අවසන් නම',
    'emailRequired': 'විද්‍යුත් තැපෑල *',
    'messageLabel': 'පණිවිඩය',
    'sendButton': 'යවන්න',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'si')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

